(() => {
	const AGENTS = [
		{
			id: "orchestrator",
			name: "Orchestrator Agent",
			purpose: "전체 작업 분해 및 에이전트 조율",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "running",
			tools: ["Task Queue", "Scheduler", "State Store"],
			lastOutput: "작업 우선순위와 병목 후보를 정리했습니다.",
		},
		{
			id: "planner",
			name: "Planner Agent",
			purpose: "요구사항 분해와 실행 계획 수립",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "running",
			tools: ["Docs", "Issue Tracker", "Mind Map"],
			lastOutput: "T1~T2 기준으로 셸과 스타일 범위를 확정했습니다.",
		},
		{
			id: "pm",
			name: "PM Agent",
			purpose: "요구사항 수집, 우선순위 정리, 역할 조율",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "idle",
			tools: ["Backlog", "Notes", "Roadmap"],
			lastOutput: "승인 지점을 문서화하고 진행 순서를 정리 중입니다.",
		},
		{
			id: "design",
			name: "Design Agent",
			purpose: "대시보드 UI/UX 설계 및 시각 규칙 정의",
			model: "google/gemini-3.1-pro",
			variant: "high",
			status: "running",
			tools: ["Figma", "Design Tokens", "Style Guide"],
			lastOutput: "다크 테마와 패널 구조를 시안으로 고정했습니다.",
		},
		{
			id: "frontend",
			name: "Frontend Agent",
			purpose: "대시보드 화면과 상호작용 컴포넌트 구현",
			model: "google/gemini-3.1-pro",
			variant: "high",
			status: "idle",
			tools: ["DOM", "Grid Layout", "Accessibility"],
			lastOutput: "정적 셸과 카드 그리드 렌더링 연결을 대기 중입니다.",
		},
		{
			id: "backend",
			name: "Backend Agent",
			purpose: "상태, 작업, 이벤트 제공 API 설계",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "idle",
			tools: ["REST API", "Validation", "Cache"],
			lastOutput: "로컬 정적 배포용 데이터 계약을 확인했습니다.",
		},
		{
			id: "workflow",
			name: "Workflow/State Agent",
			purpose: "작업 상태 전이와 재개 흐름 관리",
			model: "openai/gpt-5.5",
			variant: "default",
			status: "idle",
			tools: ["State Machine", "Event Store", "Retry Logic"],
			lastOutput: "상태 전이 규칙과 재시도 흐름을 초안화했습니다.",
		},
		{
			id: "observability",
			name: "Observability Agent",
			purpose: "로그, 메트릭, 트레이스 관측 및 요약",
			model: "openai/gpt-5.4-mini",
			variant: "default",
			status: "error",
			tools: ["Logs", "Metrics", "Traces"],
			lastOutput: "로그 패널 필터 연결에서 누락 항목을 발견했습니다.",
		},
		{
			id: "data-pipeline",
			name: "Data Pipeline Agent",
			purpose: "ETL, 수집, 변환, 저장 파이프라인 운영",
			model: "openai/gpt-5.5",
			variant: "default",
			status: "waiting",
			tools: ["ETL", "Ingestion", "Storage"],
			lastOutput: "원천 데이터 소스 연결 승인 대기 중입니다.",
		},
		{
			id: "analytics",
			name: "Analytics Agent",
			purpose: "KPI 정의와 분석 인사이트 정리",
			model: "openai/gpt-5.4-mini",
			variant: "default",
			status: "idle",
			tools: ["KPIs", "Reports", "Insights"],
			lastOutput: "대시보드 지표 후보를 우선순위별로 묶었습니다.",
		},
		{
			id: "qa",
			name: "QA Agent",
			purpose: "기능, 회귀, 통합 테스트 및 품질 검증",
			model: "openai/gpt-5.4-mini",
			variant: "default",
			status: "idle",
			tools: ["Playwright", "Cypress", "Test Cases"],
			lastOutput: "정적 셸 렌더링과 자원 로딩을 점검할 준비가 되어 있습니다.",
		},
		{
			id: "devops",
			name: "DevOps Agent",
			purpose: "배포, 환경 구성, 운영 자동화 관리",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "waiting",
			tools: ["Docker", "CI/CD", "Monitoring"],
			lastOutput: "정적 호스팅용 파일 배포 경로를 대기 중입니다.",
		},
		{
			id: "policy",
			name: "Policy/Safety Agent",
			purpose: "권한, 데이터 노출, 위험 작업 통제",
			model: "anthropic/claude-sonnet-4-6",
			variant: "high",
			status: "idle",
			tools: ["Policy Engine", "Audit Log", "Permissions"],
			lastOutput: "민감 작업 통제 기준을 점검했습니다.",
		},
	];

	const TASKS = [
		{
			id: "task-01",
			title: "HTML 셸 구성",
			agentId: "orchestrator",
			status: "completed",
			priority: "high",
			input: "대시보드 4패널 구조 요구사항",
			output: "semantic shell과 접근성 속성 초안",
		},
		{
			id: "task-02",
			title: "CSS 다크 테마 적용",
			agentId: "design",
			status: "completed",
			priority: "high",
			input: "그리드 레이아웃과 토큰 정의",
			output: "dark grid layout과 색상 변수",
		},
		{
			id: "task-03",
			title: "정적 데이터 계약 정의",
			agentId: "pm",
			status: "running",
			priority: "medium",
			input: "AGENTS / TASKS / LOGS / STRATEGIES 구조",
			output: "window 글로벌 데이터 스키마",
		},
		{
			id: "task-04",
			title: "카드 렌더링 준비",
			agentId: "frontend",
			status: "blocked",
			priority: "medium",
			input: "AGENTS 배열과 상태 배지 규칙",
			output: "렌더링 함수 입력 포맷 대기",
		},
		{
			id: "task-05",
			title: "상태 전이 규칙 검토",
			agentId: "workflow",
			status: "pending",
			priority: "low",
			input: "running / idle / error / waiting 상태",
			output: "전이 규칙 초안",
		},
		{
			id: "task-06",
			title: "로그 필터 설계",
			agentId: "observability",
			status: "running",
			priority: "medium",
			input: "INFO / WARN / ERROR 레벨",
			output: "필터 버튼과 log entry 규칙",
		},
		{
			id: "task-07",
			title: "검증 시나리오 작성",
			agentId: "qa",
			status: "pending",
			priority: "high",
			input: "브라우저 직접 열기 테스트",
			output: "검증 체크리스트",
		},
		{
			id: "task-08",
			title: "배포 경로 점검",
			agentId: "devops",
			status: "pending",
			priority: "low",
			input: "정적 파일 호스팅 조건",
			output: "배포 체크 항목",
		},
		{
			id: "task-09",
			title: "지표 후보 정리",
			agentId: "analytics",
			status: "completed",
			priority: "medium",
			input: "운영 대시보드 KPI 요구사항",
			output: "핵심 지표 목록",
		},
		{
			id: "task-10",
			title: "권한 및 안전 점검",
			agentId: "policy",
			status: "pending",
			priority: "high",
			input: "데이터 노출과 위험 작업 범위",
			output: "안전 점검 항목",
		},
	];

	const LOGS = [
		{
			time: "09:00",
			agentId: "orchestrator",
			level: "info",
			msg: "작업 분해를 시작했습니다.",
		},
		{
			time: "09:05",
			agentId: "planner",
			level: "info",
			msg: "T1과 T2를 우선 경로로 확정했습니다.",
		},
		{
			time: "09:12",
			agentId: "design",
			level: "info",
			msg: "다크 테마 토큰과 카드 비율을 정리했습니다.",
		},
		{
			time: "09:18",
			agentId: "frontend",
			level: "warn",
			msg: "렌더링 데이터가 아직 비어 있습니다.",
		},
		{
			time: "09:22",
			agentId: "backend",
			level: "info",
			msg: "정적 계약에 맞는 구조를 확인했습니다.",
		},
		{
			time: "09:28",
			agentId: "workflow",
			level: "info",
			msg: "상태 전이 표를 초안화했습니다.",
		},
		{
			time: "09:35",
			agentId: "observability",
			level: "error",
			msg: "로그 수집 경로가 아직 연결되지 않았습니다.",
		},
		{
			time: "09:42",
			agentId: "qa",
			level: "info",
			msg: "브라우저 직접 열기 검증을 준비했습니다.",
		},
		{
			time: "09:50",
			agentId: "devops",
			level: "warn",
			msg: "정적 호스팅 경로를 재확인 중입니다.",
		},
		{
			time: "09:58",
			agentId: "policy",
			level: "info",
			msg: "권한과 안전 체크리스트를 정리했습니다.",
		},
	];

	const STRATEGIES = [
		{
			id: "committee",
			label: "위원회형",
			desc: "복수 에이전트가 병렬로 검토하고 합의한다.",
			checked: true,
		},
		{
			id: "leader",
			label: "리더형",
			desc: "오케스트레이터가 우선순위를 통제한다.",
			checked: false,
		},
		{
			id: "expert",
			label: "전문가형",
			desc: "분야별 전문 에이전트가 담당 영역을 맡는다.",
			checked: true,
		},
		{
			id: "pipeline",
			label: "파이프라인형",
			desc: "단계별로 결과를 넘기며 순차 처리한다.",
			checked: false,
		},
	];

	window.AGENTS = AGENTS;
	window.TASKS = TASKS;
	window.LOGS = LOGS;
	window.STRATEGIES = STRATEGIES;
})();
